app:
  name: 'EchoGameApp'
  version: '1.0.0'
  resources_dir: './config/resources'

http:
  port: '8080'

logger:
  level: 'debug'
  log_dir: './app-log/'
  use_std_and_file: true
  add_low_priority_level_to_cmd: true
