// Code generated by scg 1,  DO NOT EDIT .
//
// EchoGame-Custom user payloads
//
// Command:
// scg
// DO NOT EDIT .

package payloads

type EchoJorePayload struct {
	Kore string `json:"kore"`
	Sore string `json:"sore"`
}
type EchoDorePayload struct {
	Kore string `json:"kore"`
	Sore string `json:"sore"`
}
