// Code generated by scg 1,  DO NOT EDIT .
//
// EchoGame-Logger interface for store
//
// Command:
// scg
// DO NOT EDIT .

package logger

type LogFunc func(message string, args ...interface{})

// Interface -.
type Interface interface {
	Debug(message interface{}, args ...interface{})
	Info(message string, args ...interface{})
	Warn(message string, args ...interface{})
	Error(message interface{}, args ...interface{})
	Fatal(message interface{}, args ...interface{})
}
