// Code generated by scg 1,  DO NOT EDIT .
//
// EchoGame-Director config
//
// Command:
// scg
// DO NOT EDIT .

package script

import (
	sd "github.com/ThCompiler/go_game_constractor/director/scriptdirector"
	"github.com/ThCompiler/go_game_constractor/scg/example/scg/echogame/manager"
	"github.com/ThCompiler/go_game_constractor/scg/example/scg/echogame/script/scenes"
)

const GoodByeCommand = "GoodeBye"

func NewEchoGameScript(manager manager.TextManager) sd.SceneDirectorConfig {
	return sd.SceneDirectorConfig{
		StartScene: &scenes.Hello{
			TextManager: manager,
		},
		GoodbyeScene: &scenes.Goodbye{
			TextManager: manager,
		},
		EndCommand: GoodByeCommand,
	}
}
