// Code generated by scg 1,  DO NOT EDIT .
//
// EchoGame-Interface for script store
//
// Command:
// scg
// DO NOT EDIT .

package store

type ScriptStore interface {
	GetText(name string) (string, error)
	SetText(name string, value string) error
	DeleteText(name string) error
	GetAllTextKeyForScript(name string) ([]string, error)
}
