// Code generated by scg 1,  DO NOT EDIT .
//
// EchoGame-Consts with name of scene text for
//
// Command:
// scg
// DO NOT EDIT .

package textsname

type SceneTextName string

const (

	// EchoText and EchoTTS of text for Echo scene
	EchoText = "EchoGame-EchoText"
	EchoTTS  = "EchoGame-EchoTTS"

	// EchoRepeatText and EchoRepeatTTS of text for EchoRepeat scene
	EchoRepeatText = "EchoGame-EchoRepeatText"
	EchoRepeatTTS  = "EchoGame-EchoRepeatTTS"

	// GoodbyeText and GoodbyeTTS of text for Goodbye scene
	GoodbyeText = "EchoGame-GoodbyeText"
	GoodbyeTTS  = "EchoGame-GoodbyeTTS"

	// HelloText and HelloTTS of text for Hello scene
	HelloText = "EchoGame-HelloText"
	HelloTTS  = "EchoGame-HelloTTS"
)
