// Code generated by scg 1,  DO NOT EDIT .
//
// EchoGame-Text usecase
//
// Command:
// scg
// DO NOT EDIT .

package usecase

import (
	consts "example/scg/internal/texts/consts/textsname"
	store "example/scg/internal/texts/store"
	"example/scg/pkg/str"

	"github.com/ThCompiler/go_game_constractor/director"
)

type TextUsecase struct {
	store store.ScriptStore
}

func NewTextUsecase(store store.ScriptStore) *TextUsecase {
	return &TextUsecase{
		store: store,
	}
}

// GetEchoText get text for echo scene with variables
func (tu *TextUsecase) GetEchoText() (director.Text, error) {
	text, err := tu.store.GetText(consts.EchoText)
	if err != nil {
		return director.Text{}, nil
	}

	tts, err := tu.store.GetText(consts.EchoTTS)
	if err != nil {
		return director.Text{}, nil
	}

	res := director.Text{
		BaseText:     text,
		TextToSpeech: tts,
	}

	return res, nil
}

// GetEchoRepeatText get text for echoRepeat scene with variables
func (tu *TextUsecase) GetEchoRepeatText(userText string) (director.Text, error) {
	text, err := tu.store.GetText(consts.EchoRepeatText)
	if err != nil {
		return director.Text{}, nil
	}

	tts, err := tu.store.GetText(consts.EchoRepeatTTS)
	if err != nil {
		return director.Text{}, nil
	}

	args := []interface{}{
		"userText", userText,
	}

	res := director.Text{
		BaseText:     str.StringFormat(text, args...),
		TextToSpeech: str.StringFormat(tts, args...),
	}

	return res, nil
}

// GetGoodbyeText get text for goodbye scene with variables
func (tu *TextUsecase) GetGoodbyeText() (director.Text, error) {
	text, err := tu.store.GetText(consts.GoodbyeText)
	if err != nil {
		return director.Text{}, nil
	}

	tts, err := tu.store.GetText(consts.GoodbyeTTS)
	if err != nil {
		return director.Text{}, nil
	}

	res := director.Text{
		BaseText:     text,
		TextToSpeech: tts,
	}

	return res, nil
}

// GetHelloText get text for hello scene with variables
func (tu *TextUsecase) GetHelloText(number int64) (director.Text, error) {
	text, err := tu.store.GetText(consts.HelloText)
	if err != nil {
		return director.Text{}, nil
	}

	tts, err := tu.store.GetText(consts.HelloTTS)
	if err != nil {
		return director.Text{}, nil
	}

	args := []interface{}{
		"number", number,
	}

	res := director.Text{
		BaseText:     str.StringFormat(text, args...),
		TextToSpeech: str.StringFormat(tts, args...),
	}

	return res, nil
}
