// Code generated by scg 1,  DO NOT EDIT .
//
// EchoGame-Director config
//
// Command:
// scg
// DO NOT EDIT .

package script

import (
	game "github.com/ThCompiler/go_game_constractor/director/scriptdirector"
	"github.com/ThCompiler/go_game_constractor/scg/example/scg/internal/script/scenes"
	"github.com/ThCompiler/go_game_constractor/scg/example/scg/internal/texts/manager"
)

const GoodByeCommand = "GoodeBye"

func NewEchoGameScript(manager manager.TextManager) game.SceneDirectorConfig {
	return game.SceneDirectorConfig{
		StartScene: &scenes.Hello{
			TextManager: manager,
		},
		GoodbyeScene: &scenes.Goodbye{
			TextManager: manager,
		},
		EndCommand: GoodByeCommand,
	}
}
