// Code generated by scg 1,  DO NOT EDIT .
//
// EchoGame-Custom user text errors
//
// Command:
// scg
// DO NOT EDIT .

package errors

import "github.com/ThCompiler/go_game_constractor/director/scene"

// text errors
var (
	DoreError = scene.BaseTextError{Message: "dore"}
)
