// Code generated by scg 1, .
//
// EchoGame-SceneStructs
//
// Command:
// scg
//.

package scenes

import (
	base_matchers "github.com/ThCompiler/go_game_constractor/director/matchers"
	"github.com/ThCompiler/go_game_constractor/director/scene"
	"github.com/ThCompiler/go_game_constractor/scg/example/scg/echogame/manager"
	"github.com/ThCompiler/go_game_constractor/scg/example/scg/echogame/script/errors"
	"github.com/ThCompiler/go_game_constractor/scg/example/scg/echogame/script/matchers"
	"github.com/ThCompiler/go_game_constractor/scg/example/scg/echogame/script/payloads"
)

type EchoRepeat struct {
	TextManager manager.TextManager
	NextScene   SceneName
}

func (sc *EchoRepeat) React(_ *scene.Context) scene.Command {
	// TODO

	sc.NextScene = EchoRepeatScene // TODO: manually set next scene after reaction
	return scene.NoCommand
}

func (sc *EchoRepeat) Next() scene.Scene {
	switch sc.NextScene {
	case EchoRepeatScene:
		return &EchoRepeat{
			TextManager: sc.TextManager,
		}
	case EchoScene:
		return &Echo{
			TextManager: sc.TextManager,
		}
	}

	return &EchoRepeat{
		TextManager: sc.TextManager,
	}
}

func (sc *EchoRepeat) GetSceneInfo(ctx *scene.Context) (scene.Info, bool) {
	var (
		userText string
	)

	//TODO

	text, _ := sc.TextManager.GetEchoRepeatText(
		userText,
	)
	return scene.Info{
		Text: text,
		ExpectedMessages: []scene.MessageMatcher{
			base_matchers.AnyMatcher,
			matchers.CheckedMatcher,
			matchers.AgreedMatcher,
		},
		Buttons: []scene.Button{
			{
				Title:   "Привет",
				Payload: &payloads.EchoRepeatDorePayload{},
			},
		},
		Err: errors.DoreError,
	}, true
}
