// Code generated by scg 1, .
//
// EchoGame-SceneStructs
//
// Command:
// scg
//.

package scenes

import (
	base_matchers "github.com/ThCompiler/go_game_constractor/director/matchers"
	"github.com/ThCompiler/go_game_constractor/director/scene"
	"github.com/ThCompiler/go_game_constractor/scg/example/scg/echogame/manager"
	"github.com/ThCompiler/go_game_constractor/scg/example/scg/echogame/script/payloads"
)

type Echo struct {
	TextManager manager.TextManager
	NextScene   SceneName
}

func (sc *Echo) React(_ *scene.Context) scene.Command {
	// TODO

	sc.NextScene = EchoScene // TODO: manually set next scene after reaction
	return scene.NoCommand
}

func (sc *Echo) Next() scene.Scene {
	switch sc.NextScene {
	case EchoRepeatScene:
		return &EchoRepeat{
			TextManager: sc.TextManager,
		}
	}

	return &Echo{
		TextManager: sc.TextManager,
	}
}

func (sc *Echo) GetSceneInfo(ctx *scene.Context) (scene.Info, bool) {

	//TODO

	text, _ := sc.TextManager.GetEchoText()
	return scene.Info{
		Text: text,
		ExpectedMessages: []scene.MessageMatcher{
			base_matchers.AnyMatcher,
		},
		Buttons: []scene.Button{
			{
				Title:   "Привет",
				Payload: &payloads.EchoDorePayload{},
			},
			{
				Title:   "Привет",
				Payload: &payloads.EchoJorePayload{},
			},
		},
		Err: base_matchers.NumberError,
	}, true
}
