// Code generated by scg 1, .
//
// EchoGame-SceneStructs
//
// Command:
// scg
//.

package scenes

import (
	"github.com/ThCompiler/go_game_constractor/director/scene"
	"github.com/ThCompiler/go_game_constractor/scg/example/scg/echogame/manager"
)

type Hello struct {
	TextManager manager.TextManager
	NextScene   SceneName
}

func (sc *Hello) React(_ *scene.Context) scene.Command {
	// TODO

	sc.NextScene = HelloScene // TODO: manually set next scene after reaction
	return scene.NoCommand
}

func (sc *Hello) Next() scene.Scene {
	switch sc.NextScene {
	case EchoScene:
		return &Echo{
			TextManager: sc.TextManager,
		}
	}

	return &Hello{
		TextManager: sc.TextManager,
	}
}

func (sc *Hello) GetSceneInfo(ctx *scene.Context) (scene.Info, bool) {
	var (
		number int64
	)

	//TODO

	text, _ := sc.TextManager.GetHelloText(
		number,
	)
	return scene.Info{
		Text:             text,
		ExpectedMessages: []scene.MessageMatcher{},
		Buttons:          []scene.Button{},
		Err:              scene.BaseSceneError{Scene: &Goodbye{TextManager: sc.TextManager}},
	}, true
}
