// Code generated by scg 1,  DO NOT EDIT .
//
// EchoGame-Custom user payloads
//
// Command:
// scg
// DO NOT EDIT .

package payloads

type EchoRepeatDorePayload struct {
	Joke string                     `json:"joke"`
	Sore EchoRepeatDorePayload_sub1 `json:"sore"`
}

type EchoRepeatDorePayload_sub1 struct {
	Nore string `json:"nore"`
}
