units:
  - ''
  - 'одно'
  - 'двух'
  - 'трёх'
  - 'четырёх'
  - 'пяти'
  - 'шести'
  - 'семи'
  - 'восьми'
  - 'девяти'
tens:
  - 'десяти'
  - 'одиннадцати'
  - 'двенадцати'
  - 'тринадцати'
  - 'четырнадцати'
  - 'пятнадцати'
  - 'шестнадцати'
  - 'семидесяти'
  - 'восемнадцати'
  - 'девятнадцати'
dozens:
  - ''
  - ''
  - 'двадцати'
  - 'тридцати'
  - 'сорока'
  - 'пятидесяти'
  - 'шестидесяти'
  - 'семидесяти'
  - 'восьмидесяти'
  - 'девяносто'
hundreds:
  - ''
  - 'сто'
  - 'двухсот'
  - 'трёхсот'
  - 'четырёхсот'
  - 'пятисот'
  - 'шестисот'
  - 'семисот'
  - 'восьмисот'
  - 'девятисот'