// Code generated by scg 1,  DO NOT EDIT .
//
// EchoGame-Custom user matchers
//
// Command:
// scg
// DO NOT EDIT .

package matchers

import "github.com/ThCompiler/go_game_constractor/director/matchers"

// RegexMatchers
var (
	CheckedMatcher = matchers.NewRegexMather("*")
)

// replace string for SelectsMatchers
const (
	AgreedMatcherString = "Da"
)

// SelectsMatchers
var (
	AgreedMatcher = matchers.NewSelectorMatcher(
		[]string{
			"da",
			"no",
		},
		AgreedMatcherString,
	)
)
