// Code generated by scg 1,  DO NOT EDIT .
//
// EchoGame-Custom user matchers
//
// Command:
// scg
// DO NOT EDIT .

package matchers

import "github.com/ThCompiler/go_game_constractor/director/matchers"

// name matched string for RegexMatchers
const (
	CheckedMatchedString = ""

	AgreedMatchedString = ""
)

// RegexMatchers
var (
	CheckedMatcher = matchers.NewRegexMather("*", CheckedMatchedString)

	AgreedMatcher = matchers.NewRegexMather("", AgreedMatchedString)
)
