// Code generated by scg 1,  DO NOT EDIT .
//
// EchoGame-Custom user matchers
//
// Command:
// scg
// DO NOT EDIT .

package matchers

import "github.com/ThCompiler/go_game_constractor/director/matchers"

// name matched string for RegexMatchers
const (
	CheckedMatchedString = "da"
)

// RegexMatchers
var (
	CheckedMatcher = matchers.NewRegexMather("*", CheckedMatchedString)
)

// replace string for SelectsMatchers
const (
	AgreedMatchedString = "Da"
)

// SelectsMatchers
var (
	AgreedMatcher = matchers.NewSelectorMatcher(
		[]string{
			"da",
			"no",
		},
		AgreedMatchedString,
	)
)
