// Code generated by scg 1, .
//
// EchoGame-SceneStructs
//
// Command:
// scg
//.

package scenes

import (
	"github.com/ThCompiler/go_game_constractor/director"
	base_matchers "github.com/ThCompiler/go_game_constractor/director/scriptdirector/matchers"
	"github.com/ThCompiler/go_game_constractor/director/scriptdirector/scene"
	loghttp "github.com/ThCompiler/go_game_constractor/pkg/logger/http"
	"github.com/ThCompiler/go_game_constractor/scg/example/scg/internal/script/errors"
	"github.com/ThCompiler/go_game_constractor/scg/example/scg/internal/script/matchers"
	"github.com/ThCompiler/go_game_constractor/scg/example/scg/internal/script/payloads"
	"github.com/ThCompiler/go_game_constractor/scg/example/scg/internal/texts/manager"
	"github.com/ThCompiler/go_game_constractor/scg/go/types"
)

const (
	// DoreEchoRepeatButtonText - text for button Dore
	DoreEchoRepeatButtonText = "Привет"
)

// EchoRepeat scene
type EchoRepeat struct {
	loghttp.LogObject
	TextManager manager.TextManager
	NextScene   SceneName
}

// React function of actions after scene has been played
func (sc *EchoRepeat) React(ctx *scene.Context) scene.Command {
	ctx.Set("sayed", types.MustConvert[string](ctx.Request.SearchedMessage))

	// TODO Write the actions after EchoRepeat scene has been played
	switch {
	// Buttons select
	case ctx.Request.NameMatched == DoreEchoRepeatButtonText && ctx.Request.WasButton:
		sc.NextScene = EchoRepeatScene

	// Matcher select
	case ctx.Request.NameMatched == base_matchers.AnyMatchedString:

	case ctx.Request.NameMatched == matchers.CheckedMatchedString:
		sc.NextScene = EchoScene
	case ctx.Request.NameMatched == matchers.AgreedMatchedString:

	default:
		sc.NextScene = EchoRepeatScene
	}

	return scene.NoCommand
}

// Next function returning next scene
func (sc *EchoRepeat) Next() scene.Scene {
	switch sc.NextScene {
	case EchoRepeatScene:
		return &EchoRepeat{
			TextManager: sc.TextManager,
		}
	case EchoScene:
		return &Echo{
			TextManager: sc.TextManager,
		}
	}

	return &EchoRepeat{
		TextManager: sc.TextManager,
	}
}

// GetSceneInfo function returning info about scene
func (sc *EchoRepeat) GetSceneInfo(ctx *scene.Context) (scene.Info, bool) {
	var (
		userText string = sc.GetSayedContextValue(ctx)
	)

	// TODO Write some actions for get data for texts

	text, _ := sc.TextManager.GetEchoRepeatText(
		userText,
	)
	return scene.Info{
		Text: text,
		ExpectedMessages: []scene.MessageMatcher{
			base_matchers.AnyMatcher,
			matchers.CheckedMatcher,
			matchers.AgreedMatcher,
		},
		Buttons: []director.Button{
			{
				Title:   DoreEchoRepeatButtonText,
				Payload: &payloads.EchoRepeatDorePayload{},
			},
		},
		Err: errors.DoreError,
	}, true
}

// GetSayedContextValue function returning value from context about scene
func (sc *EchoRepeat) GetSayedContextValue(ctx *scene.Context) string {
	return scene.GetContextAny[string](ctx, "sayed")
}
