// Code generated by scg 1,  DO NOT EDIT .
//
// EchoGame-Scenes Name
//
// Command:
// scg
// DO NOT EDIT .

package scenes

type SceneName string

const (
	// EchoScene name of $nameScene
	EchoScene = SceneName("echo")
	// EchoRepeatScene name of $nameScene
	EchoRepeatScene = SceneName("echo_repeat")
	// GoodbyeScene name of $nameScene
	GoodbyeScene = SceneName("goodbye")
	// HelloScene name of $nameScene
	HelloScene = SceneName("hello")
	// NoScene name of next scene for ending scenes
	NoScene = SceneName("_nothing_scene")
)
