// Code generated by scg 1,  DO NOT EDIT .
//
// EchoGame-Director config
//
// Command:
// scg
// DO NOT EDIT .

package script

import (
	game "github.com/ThCompiler/go_game_constractor/director"
	"github.com/ThCompiler/go_game_constractor/scg/scg/echogame/manager"
)

const GoodByeCommand = "GoodeBye"

func NewEchoGameScript(manager manager.TextManager) game.SceneDirectorConfig {
	return game.SceneDirectorConfig{
		StartScene:   &Hello{manager},
		GoodbyeScene: &Goodbye{manager},
		EndCommand:   GoodByeCommand,
	}
}
