// Code generated by scg 1, .
//
// EchoGame-Main file
//
// Command:
// scg
//.

package main

import (
	"log"

	"github.com/ThCompiler/go_game_constractor/scg/example/scg/config"
	"github.com/ThCompiler/go_game_constractor/scg/example/scg/internal/echogame"
)

// This is your application's startup file.
// All the basic settings take place already in the "internal/app" file.

func main() {
	// Configuration
	cfg, err := config.NewConfig()
	if err != nil {
		log.Fatalf("Config error: %s", err)
	}

	//_ = words.LoadWordsConstants(languages.Russia, cfg.App.ResourcesDir) // TODO: add load language

	// Run
	echogame.Run(cfg)
}
