// Code generated by scg 1,  DO NOT EDIT .
//
// EchoGame Interface for script text manager
//
// Command:
// scg
// DO NOT EDIT .

package manager

import "github.com/ThCompiler/go_game_constractor/director"

type TextManager interface {
	// GetEchoText get text for echo scene with variables
	GetEchoText() (director.Text, error)

	// GetEchoRepeatText get text for echoRepeat scene with variables
	GetEchoRepeatText(userText string) (director.Text, error)

	// GetGoodbyeText get text for goodbye scene with variables
	GetGoodbyeText() (director.Text, error)

	// GetHelloText get text for hello scene with variables
	GetHelloText(number int64) (director.Text, error)
}
