// Code generated by scg 1,  DO NOT EDIT .
//
// EchoGame-Error for store saver
//
// Command:
// scg
// DO NOT EDIT .

package storesaver

import "github.com/pkg/errors"

var ScriptAlreadySaveError = errors.New("this script has already saved")
