currencies:
  number:
    decimalCurrencyNameDeclensions:
      nominative: ['целая', '']
      genitive: ['целой', 'целых']
      dative: ['целой', 'целым']
      accusative: ['целую', 'целые']
      instrumental: ['целой', 'целыми']
      prepositional: ['целой', 'целых']
    fractionalPartNameDeclensions:
      nominative: ['', '']
      genitive: ['', '']
      dative: ['', '']
      accusative: ['', '']
      instrumental: ['', '']
      prepositional: ['', '']
    currencyNounGender:
      integerPart: 'female'
      fractionalPart: 'female'
  rub:
    decimalCurrencyNameDeclensions:
      nominative: ['рубль', '']
      genitive: ['рубля', 'рублей']
      dative: ['рублю', 'рублям']
      accusative: ['рубль', '']
      instrumental: ['рублём', 'рублями']
      prepositional: ['рубле', 'рублях']
    fractionalPartNameDeclensions:
      nominative: ['копейка', '']
      genitive: ['копейки', 'копеек']
      dative: ['копейке', 'копейкам']
      accusative: ['копейку', '']
      instrumental: ['копейкой', 'копейками']
      prepositional: ['копейке', 'копейках']
    currencyNounGender:
      integerPart: 'male'
      fractionalPart: 'female'
  usd:
    decimalCurrencyNameDeclensions:
      nominative: ['доллар', '']
      genitive: ['доллара', 'долларов']
      dative: ['доллару', 'долларам']
      accusative: ['доллар', '']
      instrumental: ['долларом', 'долларами']
      prepositional: ['долларе', 'долларах']
    fractionalPartNameDeclensions:
      nominative: ['цент', '']
      genitive: ['цента', 'центов']
      dative: ['центу', 'центам']
      accusative: ['цент', '']
      instrumental: ['центом', 'центами']
      prepositional: ['центе', 'центах']
    currencyNounGender:
      integerPart: 'male'
      fractionalPart: 'male'
  eur:
    decimalCurrencyNameDeclensions:
      nominative: ['евро', '']
      genitive: ['евро', 'евро']
      dative: ['евро', 'евро']
      accusative: ['евро', '']
      instrumental: ['евро', 'евро']
      prepositional: ['евро', 'евро']
    fractionalPartNameDeclensions:
      nominative: ['цент', '']
      genitive: ['цента', 'центов']
      dative: ['центу', 'центам']
      accusative: ['цент', '']
      instrumental: ['центом', 'центами']
      prepositional: ['центе', 'центах']
    currencyNounGender:
      integerPart: 'male'
      fractionalPart: 'male'