// Code generated by scg 1, .
//
// EchoGame-Route file
//
// Command:
// scg
//.

package v1

import (
	"github.com/ThCompiler/go_game_constractor/director/scriptdirector"
	"github.com/ThCompiler/go_game_constractor/marusia"
	"github.com/ThCompiler/go_game_constractor/marusia/runner"
	"github.com/ThCompiler/go_game_constractor/marusia/webhook"
	"github.com/ThCompiler/go_game_constractor/pkg/logger"
	loghttp "github.com/ThCompiler/go_game_constractor/pkg/logger/http"
	"github.com/gin-gonic/gin"
)

type EchoGameRoute struct {
	loghttp.LogObject
	sdc     scriptdirector.SceneDirectorConfig
	sRunner runner.ScriptRunner
	wh      *marusia.Webhook
}

func newEchoGameRoute(handler *gin.RouterGroup, sdc scriptdirector.SceneDirectorConfig,
	sRunner runner.ScriptRunner, l logger.Interface) {
	r := &EchoGameRoute{
		LogObject: loghttp.NewLogObject(l),
		sdc:       sdc,
		sRunner:   sRunner,
		wh:        webhook.NewDefaultMarusiaWebhook(l, sRunner, sdc),
	}

	handler.POST("/echo_game", r.wh.GinHandleFunc)
}
