// Code generated by scg 1,  DO NOT EDIT .
//
// EchoGame Interface for script text manager
//
// Command:
// scg
// DO NOT EDIT .

package manager

import "github.com/ThCompiler/go_game_constractor/director/scene"

type TextManager interface {

	// GetEchoText get text for echo scene with variables
	GetEchoText() (scene.Text, error)

	// GetEchoRepeatText get text for echoRepeat scene with variables
	GetEchoRepeatText(userText string) (scene.Text, error)

	// GetGoodbyeText get text for goodbye scene with variables
	GetGoodbyeText() (scene.Text, error)

	// GetHelloText get text for hello scene with variables
	GetHelloText(number int64) (scene.Text, error)
}
